#!/usr/bin/env bash
# Klipper module
# Main section to install Klipper on top of OctoPi
# Written by Guy Sheffer <guysoft@gmail.com>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

export LC_ALL=C


source /common.sh
install_cleanup_trap

# Klipper repo
[ -n "$KLIPPER_REPO" ] || KLIPPER_REPO=https://github.com/KevinOConnor/klipper.git
[ -n "$KLIPPER_BRANCH" ] || KLIPPER_BRANCH=master
[ -n "$KLIPPER_DEPTH" ] || KLIPPER_DEPTH=1

# OctoprintKlipper plugin
[ -n "$KLIPPER_OCTOKLIPPER_URL" ] || KLIPPER_OCTOKLIPPER_URL="https://github.com/thelastWallE/OctoprintKlipperPlugin/archive/master.zip"

# Install Klipper
apt-get -y --allow-downgrades --allow-remove-essential --allow-change-held-packages install virtualenv python-dev libffi-dev build-essential libncurses-dev libusb-dev avrdude gcc-avr binutils-avr avr-libc stm32flash dfu-util libnewlib-arm-none-eabi gcc-arm-none-eabi binutils-arm-none-eabi libusb-1.0

pushd /home/pi
  # Mostly taken from klipper/scripts/install-octopi.sh
  sudo -u pi git clone -b "$KLIPPER_BRANCH" --depth $KLIPPER_DEPTH "$KLIPPER_REPO" klipper
  sudo -u pi virtualenv -p python2 klippy-env
  sudo -u pi klippy-env/bin/pip install -r klipper/scripts/klippy-requirements.txt

  cp klipper/scripts/klipper-start.sh /etc/init.d/klipper
  chmod 755 /etc/init.d/klipper
  update-rc.d klipper defaults

  cp -a /files/klipper/printer.cfg .
  chown pi:pi printer.cfg
  chmod 644 printer.cfg
popd

cp /files/klipper/default /etc/default/klipper
chmod 644 /etc/default/klipper

# Install plugin
sudo -u pi /home/pi/oprint/bin/pip install "${KLIPPER_OCTOKLIPPER_URL}"

# Merge config
sudo -u pi /home/pi/oprint/bin/python /files/merge-settings.py /files/octoprint/config.yaml /home/pi/.octoprint/config.yaml
